### ISSUE TITLE
knife-ec-backup doesn't work on latest ChefDK

### ISSUE THREAD

**Issue by danielcbright** [chef/knife-ec-backup#129]
# Version:

ChefDK 4.x

# Environment:

Windows 10, Mac OSX, Linux

# Scenario:

Try to run `chef gem install knife-ec-backup`, it fails with an error.

# Steps to Reproduce:

Run:

```
chef gem install knife-ec-backup
```

# Expected Result:

I wanted it to actually install.

# Actual Result:

It didn't install, it instead errors with:

```
[root@mylaptop tmp]# chef gem install knife-ec-backup -- --with-pg-config=/opt/opscode/embedded/postgresql/9.6/bin/pg_config            WARNING:  You don't have /root/.chefdk/gem/ruby/2.6.0/bin in your PATH,
          gem executables will not run.
Building native extensions with: '--with-pg-config=/opt/opscode/embedded/postgresql/9.6/bin/pg_config'
This could take a while...
ERROR:  Error installing knife-ec-backup:
        ERROR: Failed to build gem native extension.
    current directory: /root/.chefdk/gem/ruby/2.6.0/gems/pg-1.1.4/ext
/opt/chefdk/embedded/bin/ruby -I /opt/chefdk/embedded/lib/ruby/2.6.0 -r ./siteconf20190724-14239-bith1h.rb extconf.rb --with-pg-config\=/opt/opscode/embedded/postgresql/9.6/bin/pg_config
Using config values from /opt/opscode/embedded/postgresql/9.6/bin/pg_config
checking for libpq-fe.h... yes
checking for libpq/libpq-fs.h... yes
checking for pg_config_manual.h... yes
checking for PQconnectdb() in -lpq... yes
checking for PQsetSingleRowMode()... yes
checking for PQconninfo()... yes
checking for PQsslAttribute()... yes
checking for PQencryptPasswordConn()... no
checking for timegm()... yes
checking for rb_gc_adjust_memory_usage()... yes
checking for PG_DIAG_TABLE_NAME in libpq-fe.h... yes
checking for unistd.h... yes
checking for inttypes.h... yes
checking for C99 variable length arrays... yes
creating extconf.h
creating Makefile
current directory: /root/.chefdk/gem/ruby/2.6.0/gems/pg-1.1.4/ext
make "DESTDIR=" clean
current directory: /root/.chefdk/gem/ruby/2.6.0/gems/pg-1.1.4/ext
make "DESTDIR="
compiling gvl_wrappers.c
compiling pg.c
compiling pg_binary_decoder.c
compiling pg_binary_encoder.c
compiling pg_coder.c
compiling pg_connection.c
compiling pg_copy_coder.c
compiling pg_errors.c
compiling pg_result.c
compiling pg_text_decoder.c
compiling pg_text_encoder.c
compiling pg_tuple.c
compiling pg_type_map.c
compiling pg_type_map_all_strings.c
compiling pg_type_map_by_class.c
compiling pg_type_map_by_column.c
compiling pg_type_map_by_mri_type.c
compiling pg_type_map_by_oid.c
compiling pg_type_map_in_ruby.c
compiling util.c
linking shared-object pg_ext.so
/bin/ld: unrecognized option '--compress-debug-sections=zlib'
/bin/ld: use the --help option for usage information
collect2: error: ld returned 1 exit status
make: *** [pg_ext.so] Error 1
make failed, exit code 2
Gem files will remain installed in /root/.chefdk/gem/ruby/2.6.0/gems/pg-1.1.4 for inspection.
Results logged to /root/.chefdk/gem/ruby/2.6.0/extensions/x86_64-linux/2.6.0/pg-1.1.4/gem_make.out
```

**Comment by vsingh-msys** [comment]
@danielcbright As I can see it requires `pg` gem which builds on native `PostgreSQL` so need to install `libpq-dev` on the host machine as well.
In order to fix it following command may be helpful for Linux node?

```
sudo apt-get install postgresql postgresql-contrib libpq-dev
```
Thanks!

**Comment by chef-davin** [comment]
@vsingh-msys I'm trying to get knife-ec-backup running from ChefDK on my mac.  Do I have to have postgresql installed there, or are there other ways to get the necessary libs installed or to ignore that dependency when installing the tool?

**Comment by lamont-granquist** [comment]
You shouldn't be installing knife-ec-backup with postgres on your mac.

To migrate off of a chef-server using knife-ec-backup you should follow these instructions:

https://blog.chef.io/migrating-chef-server-knife-ec-backup-knife-tidy/

Note that those setup requirements are specific to RHEL/Ubuntu because those setup instructions are intended to be run only on the chef server and not on your mac.

If you are installing on your mac in order to migrate an organization off of hosted chef then you do not have the master 'pivotal' postgres password (which would expose every customer's database on hosted chef) and cannot use the postgres options at all.  Just `gem install knife-ec-backup` without the pg option and then do not use the `--with-user-sql` and `--with-key-sql` options at all.

If you really want it installed on your mac then you can try installing the dev deps with homebrew or something like that in which case you need to point the `--with-pg-config` option at the postgres from homebrew.  If you go down this road you may wind up with library conflicts between e.g. the version of openssl installed in homebrew and the one installed in omnibus running the ruby that knife-ec-backup.  If that happens, you probably need to give up.   The alternative is to get postgres libraries installed into your omnibus installation, which means you have to compile the postgres libraries from source and link them against the libs in /opt/chefdk/embedded/lib by hand, and then correctly get the pg gem installed with the options to link against that postgres library.  I thought we used to have a recipe in the postgres cookbook to do that but either I'm misremembering history or that was removed from that cookbook, so there's no easy path to doing that if you hit this problem.  If you wind up here this is pretty much a nightmare, so I'd avoid even thinking of going down this route.  Omnibus is really great for the 99% use case until you wind up needing to do this.

No matter where you wind up here though this isn't a bug in this cookbook.

**Comment by btm** [comment]
@lamont-granquist's last response covers how unsupported it is getting this installed in another omnibus build that doesn't have postgresql already built in (ruby gem dependencies are hard).

I'll add a clarifying note in the README about how this is unsupported in #146, but with a tip too.
